# Generated by Django 5.1 on 2024-09-06 20:37

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address', max_length=254, unique=True, verbose_name='email')),
                ('full_name', models.CharField(blank=True, help_text='Введите ФИО клиента', max_length=255, null=True, verbose_name='full_name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введите телефон клиента', max_length=15, null=True, region='RU', verbose_name='phone_number')),
                ('city', models.CharField(blank=True, help_text='Введите город клиента', max_length=50, null=True, verbose_name='Город')),
                ('comment', models.TextField(blank=True, help_text='Введите комментарий клиента', null=True, verbose_name='Комментарий')),
                ('company', models.CharField(blank=True, help_text='Введите компанию клиента', max_length=100, null=True, verbose_name='компания')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, активен клиент или нет', verbose_name='активный или нет')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение для сообщения', null=True, upload_to='mailsender/photo', verbose_name='Изображение')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название рассылки', max_length=100, verbose_name='Название рассылки')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время первой отправки рассылки', verbose_name='Дата и время первой отправки рассылки')),
                ('end_time', models.DateTimeField(blank=True, help_text='Дата и время окончания рассылки', null=True, verbose_name='Дата и время окончания рассылки')),
                ('frequency', models.CharField(choices=[('once', 'Один раз'), ('day', 'Раз в день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], help_text='Выберите периодичность', max_length=10, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('finished', 'Завершена')], help_text='Выберите статус рассылки', max_length=10, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(related_name='mailing_lists', to='mailsender.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_lists', to='mailsender.message')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='attempt_time')),
                ('status', models.BooleanField(verbose_name='status')),
                ('response', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailsender.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailsender.message')),
            ],
            options={
                'verbose_name': 'Попытка отправки сообщения',
                'verbose_name_plural': 'Попытки отправки сообщений',
            },
        ),
    ]
