# Generated by Django 4.2.2 on 2024-09-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0003_client_owner_mailinglist_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'permissions': [('can_edit_status', 'Can edit Status')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
