# Generated by Django 4.2.2 on 2024-09-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0005_message_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', models.CharField(max_length=100, verbose_name='Содержание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('count_review', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ['title', 'count_review'],
            },
        ),
    ]
